In [1]:
import pandas as pd
import warnings
from scipy.sparse import hstack
from sklearn.ensemble import RandomForestClassifier

In [2]:
warnings.filterwarnings('ignore')

In [5]:
data = pd.read_csv(r'C:\Users\Shivani\OneDrive\Documents\course remmondation system')

PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Shivani\\OneDrive\\Documents\\course remmondation system'

In [ ]:
data.head(2)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance
1,1113822,Complete GST Course & Certification - Grow You...,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance

In [ ]:
data.shape

(3678, 12)

In [ ]:
data.isnull().sum()

course_id              0
course_title           0
url                    0
is_paid                0
price                  0
num_subscribers        0
num_reviews            0
num_lectures           0
level                  0
content_duration       0
published_timestamp    0
subject                0
dtype: int64

In [ ]:
print(data.duplicated().sum())

6

In [ ]:
data[data.duplicated()]

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject
787,837322,Essentials of money value: Get a financial Life !,https://www.udemy.com/essentials-of-money-value/,True,20,0,0,20,All Levels,0.616667,2016-05-16T18:28:30Z,Business Finance
788,1157298,Introduction to Forex Trading Business For Beg...,https://www.udemy.com/introduction-to-forex-tr...,True,20,0,0,27,Beginner Level,1.500000,2017-04-23T16:19:01Z,Business Finance
894,1035638,Understanding Financial Statements,https://www.udemy.com/understanding-financial-...,True,25,0,0,10,All Levels,1.000000,2016-12-15T14:56:17Z,Business Finance
1100,1084454,CFA Level 2- Quantitative Methods,https://www.udemy.com/cfa-level-2-quantitative...,True,40,0,0,35,All Levels,5.500000,2017-07-02T14:29:35Z,Business Finance
1473,185526,MicroStation - Células,https://www.udemy.com/microstation-celulas/,True,20,0,0,9,Beginner Level,0.616667,2014-04-15T21:48:55Z,Graphic Design
2561,28295,Learn Web Designing & HTML5/CSS3 Essentials in...,https://www.udemy.com/build-beautiful-html5-we...,True,75,43285,525,24,All Levels,4.000000,2013-01-03T00:55:31Z,Web Development

In [ ]:
data["course_title"][2561]

'Learn Web Designing & HTML5/CSS3 Essentials in 4-Hours'

In [ ]:
data.shape

(3678, 12)

In [ ]:
data.columns

Index(['course_id', 'course_title', 'url', 'is_paid', 'price',
       'num_subscribers', 'num_reviews', 'num_lectures', 'level',
       'content_duration', 'published_timestamp', 'subject'],
      dtype='object')

In [ ]:
def pop_rem(data):
 data['pop_score']= 0.6*data['num_subscribers']+0.4*data['num_reviews']
 d_sort=data.sort_values(by='pop_score',ascending=False)
 return d_sort

In [ ]:
pop_rem(data)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,pop_score
2827,41295,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,False,0,268923,8629,45,All Levels,10.500000,2013-02-14T07:03:41Z,Web Development,164805.4
3032,59014,Coding for Entrepreneurs Basic,https://www.udemy.com/coding-for-entrepreneurs...,False,0,161029,279,27,Beginner Level,3.500000,2013-06-09T15:51:55Z,Web Development,96729.0
3230,625204,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,True,200,121584,27445,342,All Levels,43.000000,2015-11-02T21:13:27Z,Web Development,83928.4
3232,764164,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,True,200,114512,22412,304,All Levels,30.500000,2016-03-08T22:28:36Z,Web Development,77672.0
2783,173548,Build Your First Website in 1 Week with HTML5 ...,https://www.udemy.com/build-your-first-website...,False,0,120291,5924,30,Beginner Level,3.000000,2014-04-08T16:21:30Z,Web Development,74544.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...
784,1271182,Practical Film Financing: Finding & Pitching I...,https://www.udemy.com/indiefilm-financing/,True,100,0,0,9,Beginner Level,1.000000,2017-07-05T21:46:55Z,Business Finance,0.0
783,1169196,"Credit concepts and checklist for bankers, cre...",https://www.udemy.com/credit-concepts-and-chec...,True,20,0,0,10,Beginner Level,2.500000,2017-04-24T14:56:01Z,Business Finance,0.0
782,1221942,Basic Bookkeeping,https://www.udemy.com/basic-bookkeeping-course/,True,35,0,0,12,Beginner Level,0.733333,2017-05-23T16:20:18Z,Business Finance,0.0
1472,181268,Photoshop: Creando elemental de aire,https://www.udemy.com/photoshop-creando-elemen...,True,20,0,0,5,Beginner Level,1.000000,2014-04-01T21:50:32Z,Graphic Design,0.0
1473,185526,MicroStation - Células,https://www.udemy.com/microstation-celulas/,True,20,0,0,9,Beginner Level,0.616667,2014-04-15T21:48:55Z,Graphic Design,0.0

In [ ]:
#content recommendation

In [ ]:
!pip install neattext
import neattext.functions as nfx

Collecting neattext
  Downloading neattext-0.1.3-py3-none-any.whl.metadata (12 kB)
Downloading neattext-0.1.3-py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.7/114.7 kB 2.9 MB/s eta 0:00:0000:01
Installing collected packages: neattext
Successfully installed neattext-0.1.3

In [ ]:
data['best_recom']=data['course_title'] + data['num_subscribers'].astype(str)

In [ ]:
data['course_title']=data['course_title'].apply(nfx.remove_stopwords)
data['course_title']=data['course_title'].apply(nfx.remove_special_characters)

In [ ]:
data.head(2)

,course_id,course_title,url,is_paid,price,num_subscribers,num_reviews,num_lectures,level,content_duration,published_timestamp,subject,pop_score,best_recom
0,1070968,Ultimate Investment Banking Course,https://www.udemy.com/ultimate-investment-bank...,True,200,2147,23,51,All Levels,1.5,2017-01-18T20:58:58Z,Business Finance,1297.4,Ultimate Investment Banking Course2147
1,1113822,Complete GST Course Certification Grow Practice,https://www.udemy.com/goods-and-services-tax/,True,75,2792,923,274,All Levels,39.0,2017-03-09T16:34:20Z,Business Finance,2044.4,Complete GST Course & Certification - Grow You...

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
cv=CountVectorizer(max_features=3000)
vectors=cv.fit_transform(data['best_recom'])

In [ ]:
print(vectors)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 20731 stored elements and shape (3678, 3000)>
  Coords	Values
  (0, 2877)	1
  (0, 2234)	1
  (0, 218)	1
  (0, 973)	1
  (1, 842)	1
  (1, 2140)	1
  (1, 935)	1
  (1, 665)	1
  (1, 2135)	1
  (1, 2976)	1
  (1, 564)	1
  (2, 1883)	1
  (2, 2389)	1
  (2, 1947)	1
  (2, 540)	1
  (2, 155)	1
  (2, 892)	1
  (3, 1883)	1
  (3, 244)	1
  (3, 2828)	1
  (3, 2553)	1
  (3, 149)	1
  (3, 2193)	1
  (3, 1727)	1
  (4, 2976)	1
  :	:
  (3674, 2172)	1
  (3674, 2954)	1
  (3674, 2434)	1
  (3674, 789)	1
  (3674, 2935)	1
  (3674, 190)	1
  (3674, 1218)	1
  (3674, 2957)	1
  (3675, 155)	1
  (3675, 2290)	1
  (3675, 528)	1
  (3675, 2895)	1
  (3676, 2976)	1
  (3676, 1045)	1
  (3676, 2455)	1
  (3676, 144)	1
  (3676, 1535)	1
  (3676, 1088)	1
  (3676, 162)	1
  (3677, 244)	1
  (3677, 2828)	1
  (3677, 528)	1
  (3677, 2895)	1
  (3677, 2936)	1
  (3677, 773)	1

In [ ]:
vectors.shape

(3678, 3000)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
similarity=cosine_similarity(vectors)

In [ ]:
similarity

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.        , 0.14285714,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.20412415, 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.20412415, ..., 1.        , 0.        ,
        0.40824829],
       [0.        , 0.14285714, 0.        , ..., 0.        , 1.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.40824829, 0.        ,
        1.        ]])

In [ ]:
similarity[0]

array([1., 0., 0., ..., 0., 0., 0.])

In [ ]:
sorted(enumerate(similarity[0]),reverse=True,key=lambda x:x[1])[1:6]

[(417, np.float64(0.5773502691896258)),
 (39, np.float64(0.4472135954999579)),
 (722, np.float64(0.4082482904638631)),
 (137, np.float64(0.35355339059327373)),
 (227, np.float64(0.35355339059327373))]

In [ ]:
data.iloc[39]

course_id                                                         965832
course_title                     Complete Investment Banking Course 2017
url                    https://www.udemy.com/the-complete-investment-...
is_paid                                                             True
price                                                                195
num_subscribers                                                     8575
num_reviews                                                          809
num_lectures                                                         110
level                                                         All Levels
content_duration                                                     5.5
published_timestamp                                 2016-10-10T16:16:26Z
subject                                                 Business Finance
pop_score                                                         5468.6
best_recom               The Complete Investment Banking Course 20178575
Name: 39, dtype: object

In [ ]:
def content_rec_df(course, top_n=10):
    #clean data
    processed_course = nfx.remove_stopwords(course)
    processed_course = nfx.remove_special_characters(processed_course)

    #check if course still exists in dataframe
    if processed_course not in data['course_title'].values:
        print(f"Course '{course}' not found.")
        return pd.DataFrame()

    course_index = data[data['course_title'] == processed_course].index[0]
    distances = similarity[course_index]
    top_courses = sorted(enumerate(distances), reverse=True, key=lambda x: x[1])[1:top_n+1]

    recs_df = pd.DataFrame({
        'course_title': [data.iloc[i[0]].course_title for i in top_courses],
        'similarity_score': [i[1] for i in top_courses],
        'num_subscribers': [data.iloc[i[0]].num_subscribers for i in top_courses],
        'num_reviews': [data.iloc[i[0]].num_reviews for i in top_courses],
        'pop_score': [data.iloc[i[0]].pop_score for i in top_courses]
    })

    return recs_df

In [ ]:
recs_df = content_rec_df('Ultimate Investment Banking Course')
recs_df

,course_title,similarity_score,num_subscribers,num_reviews,pop_score
0,Investment Banking Recruitment Series,0.577350,17,6,12.6
1,Complete Investment Banking Course 2017,0.447214,8575,809,5468.6
2,Investment Banking Operations Securities Trad...,0.408248,267,9,163.8
3,Intro Investment Banking MA IPO Modeling Free...,0.353553,1922,149,1212.8
4,Investment Banking Land Job Wall Street,0.353553,1218,30,742.8
5,Business Banking 101,0.353553,132,3,80.4
6,Ultimate JavaScript Strings,0.353553,3142,117,1932.0
7,Ultimate JavaScript Objects,0.353553,1525,43,932.2
8,Ultimate Beginner Guitar Masterclass,0.288675,8113,79,4899.4
9,Stock Market investment Practical Accounting,0.250000,1120,6,674.4

In [ ]:
numerical_features = recs_df[['similarity_score', 'num_subscribers', 'num_reviews', 'pop_score']].values

In [ ]:
cv = CountVectorizer(max_features=3000)
text_vectors = cv.fit_transform(recs_df['course_title'])

In [ ]:
X = hstack([text_vectors, numerical_features])

In [ ]:
def create_labels(row):
    if row['similarity_score']>=0.9:
        return 2
    if row['similarity_score']>=0.3:
        return 1
    else:
        return 0

In [ ]:
recs_df['relevance'] = recs_df.apply(create_labels, axis=1)
y = recs_df['relevance']

In [ ]:
recs_df

,course_title,similarity_score,num_subscribers,num_reviews,pop_score,relevance
0,Investment Banking Recruitment Series,0.577350,17,6,12.6,1
1,Complete Investment Banking Course 2017,0.447214,8575,809,5468.6,1
2,Investment Banking Operations Securities Trad...,0.408248,267,9,163.8,1
3,Intro Investment Banking MA IPO Modeling Free...,0.353553,1922,149,1212.8,1
4,Investment Banking Land Job Wall Street,0.353553,1218,30,742.8,1
5,Business Banking 101,0.353553,132,3,80.4,1
6,Ultimate JavaScript Strings,0.353553,3142,117,1932.0,1
7,Ultimate JavaScript Objects,0.353553,1525,43,932.2,1
8,Ultimate Beginner Guitar Masterclass,0.288675,8113,79,4899.4,0
9,Stock Market investment Practical Accounting,0.250000,1120,6,674.4,0

In [ ]:
rf = RandomForestClassifier(random_state=42)
rf.fit(X, y)

RandomForestClassifier(random_state=42)

In [ ]:
predictions = rf.predict(X)
recs_df['predicted_suitability'] = predictions

In [ ]:
recs_df

,course_title,similarity_score,num_subscribers,num_reviews,pop_score,relevance,predicted_suitability
0,Investment Banking Recruitment Series,0.577350,17,6,12.6,1,1
1,Complete Investment Banking Course 2017,0.447214,8575,809,5468.6,1,1
2,Investment Banking Operations Securities Trad...,0.408248,267,9,163.8,1,1
3,Intro Investment Banking MA IPO Modeling Free...,0.353553,1922,149,1212.8,1,1
4,Investment Banking Land Job Wall Street,0.353553,1218,30,742.8,1,1
5,Business Banking 101,0.353553,132,3,80.4,1,1
6,Ultimate JavaScript Strings,0.353553,3142,117,1932.0,1,1
7,Ultimate JavaScript Objects,0.353553,1525,43,932.2,1,1
8,Ultimate Beginner Guitar Masterclass,0.288675,8113,79,4899.4,0,0
9,Stock Market investment Practical Accounting,0.250000,1120,6,674.4,0,0